image: busybox:latest

stages:
  - infra
  - kube
  - destroy

Deploy Infra:
  stage: infra
  script:
    - echo "Start infrustructure deployment"
    - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh
    - chmod +x install.sh && ./install.sh
    - yc init --token ${YC_OAUTH_TOKEN} --cloud-id ${YC_CLOUD_ID} --folder-id ${YC_FOLDER_ID}
    - yc config list

Deploy Kubernetes:
  stage: kube
  script:
    - echo "Do your deploy here"

Destroy:
  stage: destroy
  script:
    - echo "Do your deploy here"
  when: manual