image: ubuntu:16.04

stages:
  - infra
  - kube
  
before_script:
  - apt-get update
  - apt-get install -y curl jq
  - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - ~/yandex-cloud/bin/yc config set token ${YC_OAUTH_TOKEN}
  - ~/yandex-cloud/bin/yc config set cloud-id ${YC_CLOUD_ID}
  - ~/yandex-cloud/bin/yc config set folder-id ${YC_FOLDER_ID}
  - chmod +x infra/*.sh
  - chmod +x kube/*.sh

Deploy Infra:
  stage: infra
  script:
    - echo "Start infra deployment."
    - ./infra/yc-vpc.sh
    - ./infra/yc-compute.sh
    - echo "Infra deployed."

Destroy:
  stage: infra
  script:
    - echo "Destroy infra"
    - ./ci/destroy.sh
  when: manual

Deploy Kubernetes:
  stage: kube
  script:
    - echo "Start kubernetes deployment"
    - ./kube/make_inventory.sh
    - cat ./kube/kube_hosts.ini
