image: williamyeh/ansible:ubuntu16.04

stages:
  - infra
  - kube
  
before_script:
  - apt-get update > /dev/null
  - apt-get install -y curl jq ssh git > /dev/null
  - pip install netaddr > /dev/null

  - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - export PATH="~/yandex-cloud/bin:$PATH"
  - yc config set token ${YC_OAUTH_TOKEN}
  - yc config set cloud-id ${YC_CLOUD_ID}
  - yc config set folder-id ${YC_FOLDER_ID}

  - chmod +x infra/*.sh
  - chmod +x kube/*.sh

  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

Deploy Infra:
  stage: infra
  script:
    - echo "Start infra deployment."
    - ./infra/yc-vpc.sh
    - ./infra/yc-compute.sh
    - echo "Infra deployed."
  only:
    - master

Destroy:
  stage: infra
  script:
    - echo "Destroy infra"
    - ./infra/destroy.sh
  only:
    - master
  when: manual

Deploy Kubernetes:
  stage: kube
  script:
    - echo "Looks like YC VMs need some time to become ready after deployment..."
    - echo "So, will sleep for 200 seconds..."
    - sleep 200
    - echo "Start kubernetes deployment"
    - ./kube/make_inventory.sh
    - cat ./kube/kubespray_inventory/kube_hosts.ini
    - cd kube
    - git clone https://github.com/kubernetes-sigs/kubespray.git
    - cp -r kubespray_inventory kubespray/inventory/
    - cd kubespray
    - export ANSIBLE_FORCE_COLOR=1
    - ansible-playbook -i inventory/kubespray_inventory/kube_hosts.ini --user yc-user --become --become-user=root cluster.yml
    - echo "Kubernetes deployed."
  only:
    - master
  artifacts:
    name: kube_config
    paths:
      - ./kube/kubespray/inventory/kubespray_inventory/artifacts/admin.conf
