image: ubuntu:16.04

stages:
  - infra
  - kube
  
before_script:
  - apt-get update
  - apt-get install -y curl jq ssh git
  - pip install netaddr

  - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - ~/yandex-cloud/bin/yc config set token ${YC_OAUTH_TOKEN}
  - ~/yandex-cloud/bin/yc config set cloud-id ${YC_CLOUD_ID}
  - ~/yandex-cloud/bin/yc config set folder-id ${YC_FOLDER_ID}

  - chmod +x infra/*.sh
  - chmod +x kube/*.sh

  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H github.com >> ~/.ssh/known_hosts

Deploy Infra:
  stage: infra
  script:
    - echo "Start infra deployment."
    - ./infra/yc-vpc.sh
    - ./infra/yc-compute.sh
    - echo "Infra deployed."

Destroy:
  stage: infra
  script:
    - echo "Destroy infra"
    - ./infra/destroy.sh
  when: manual

Deploy Kubernetes:
  image: williamyeh/ansible:ubuntu16.04
  stage: kube
  script:
    - echo "Start kubernetes deployment"
    - ./kube/make_inventory.sh
    - cat ./kube/kube_hosts.ini
    - cd kube
    - git clone https://github.com/kubernetes-sigs/kubespray.git
    - cp kube_hosts.ini kubespray/inventory/sample/kube_hosts.ini
    - cd kubespray
    - export ANSIBLE_FORCE_COLOR=1
    - ansible-playbook -i inventory/sample/kube_hosts.ini --user yc-user --become --become-user=root cluster.yml
