image: williamyeh/ansible:ubuntu16.04

variables:
  TF_VAR_yc_token: ${YC_OAUTH_TOKEN}
  TF_VAR_yc_cloud_id: ${YC_CLOUD_ID}
  TF_VAR_yc_folder_id: ${YC_FOLDER_ID}

stages:
  - validate
  - infra
  - kube
  - postdeploy
  - gluster
  - destroy
  
before_script:
  - apt-get update > /dev/null
  - apt-get install -y curl jq ssh git unzip > /dev/null
  - pip install netaddr > /dev/null

  - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip > /dev/null
  - unzip terra*
  - mv terraform /usr/local/bin
  - rm -rf terra*

  - curl -s https://terraform-provider-yandex.website.yandexcloud.net/terraform-provider-yandex/install.sh | bash

  - chmod +x infra/*.sh

  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - echo 'Ansible refuses to read from a world-writeable folder, hence' && chmod -v 700 $(pwd)/postdeploy/ansible

tf_validate:
  stage: validate
  only:
    - master
  script:
    - cd infra
    - terraform init -reconfigure -get=true -get-plugins=true
    - terraform validate -check-variables=true

Deploy Infra:
  stage: infra
  script:
    - cd infra
    - terraform init -reconfigure -get=true -get-plugins=true
    - terraform apply -input=false -auto-approve
    - terraform output -json > tf_output.json
  only:
    - master
  artifacts:
    name: tf_config
    paths:
      - ./infra/terraform.tfstate
      - ./infra/tf_output.json

Deploy Kubernetes:
  stage: kube
  script:
    - echo "Looks like YC VMs need some time to become ready after deployment..."
    - echo "So, will sleep for 200 seconds..."
    - sleep 200
    - echo "Start kubernetes deployment"
    - cd infra
    - ./make_ansible_inventory.sh
    - cd ./../kube
    - cat ./kubespray_inventory/kube_hosts.ini
    - git clone https://github.com/kubernetes-sigs/kubespray.git
    - cd kubespray
    - git fetch && git fetch --tags
    - git checkout v2.8.2
    - cp -r ../kubespray_inventory inventory/
    - export ANSIBLE_FORCE_COLOR=1
    - ansible-playbook -i inventory/kubespray_inventory/kube_hosts.ini --user centos --become --become-user=root --timeout 30 cluster.yml
    - echo "Kubernetes deployed."
  only:
    - master
  artifacts:
    name: kube_config
    paths:
      - ./kube/kubespray/inventory/kubespray_inventory/artifacts/admin.conf

Kubernetes Postdeploy:
  stage: postdeploy
  script:
    - echo "Start kubernetes post-deployment steps."
    - cd infra
    - ./make_ansible_inventory.sh
    - cd ..
    - cp -r kube/kubespray_inventory postdeploy/ansible/inventory/
    - cd postdeploy/ansible
    - export ANSIBLE_FORCE_COLOR=1
    - ansible-playbook -i inventory/kubespray_inventory/kube_hosts.ini -e ansible_user=centos playbooks/postdeploy.yml
    - echo "Kubernetes post-deployment finished."
  only:
    - master
  artifacts:
    name: kube_admin_token
    paths:
      - ./postdeploy/ansible/inventory/kubespray_inventory/artifacts/token.txt

Deploy GlusterFS:
  stage: gluster
  script:
    - echo "Start GlusterFS & Heketi deployment"
    - cd infra
    - ./make_ansible_inventory.sh
    - cd ./../kube
    - cat ./kubespray_inventory/kube_hosts.ini
    - rm -rf kubespray
    - git clone https://github.com/kubernetes-sigs/kubespray.git
    - cd kubespray
#    - git fetch && git fetch --tags
#    - git checkout v2.8.2
    - cp -r ../kubespray_inventory inventory/
    - export ANSIBLE_FORCE_COLOR=1
    - ansible-playbook -i inventory/kubespray_inventory/kube_hosts.ini --user centos --become --become-user=root --timeout 30 contrib/network-storage/heketi/heketi.yml
    - echo "Kubernetes deployed."
  only:
    - master

Destroy:
  stage: destroy
  script:
    - cd infra
    - terraform init -reconfigure -get=true -get-plugins=true
    - terraform destroy -input=false -auto-approve
  only:
    - master
  when: manual
  artifacts:
    name: tf_config
    paths:
      - ./infra/terraform.tfstate