image: busybox:latest

stages:
  - infra
  - kube
  - destroy

Deploy Infra:
  stage: infra
  script:
    - echo "Do your deploy here"

Deploy Kubernetes:
  stage: kube
  script:
    - echo "Do your deploy here"

Destroy:
  stage: destroy
  script:
    - echo "Do your deploy here"
  when: manual