image: ubuntu:16.04

stages:
  - infra
  - kube
  - destroy
  
before_script:
  - apt-get update
  - apt-get install -y -qq curl
  - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - ~/yandex-cloud/bin/yc config set token ${YC_OAUTH_TOKEN}
  - ~/yandex-cloud/bin/yc config set cloud-id ${YC_CLOUD_ID}
  - ~/yandex-cloud/bin/yc config set folder-id ${YC_FOLDER_ID}
  - ~/yandex-cloud/bin/yc config list

Deploy Infra:
  stage: infra
  script:
    - echo "Start infrustructure deployment"

Deploy Kubernetes:
  stage: kube
  script:
    - echo "Do your deploy here"

Destroy:
  stage: destroy
  script:
    - echo "Do your deploy here"
  when: manual