image: ubuntu:16.04

stages:
  - infra
  - kube
  - destroy
  
before_script:
  - apt-get update
  - apt-get install -y curl jq
  - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - ~/yandex-cloud/bin/yc config set token ${YC_OAUTH_TOKEN}
  - ~/yandex-cloud/bin/yc config set cloud-id ${YC_CLOUD_ID}
  - ~/yandex-cloud/bin/yc config set folder-id ${YC_FOLDER_ID}
  - chmod +x ci/*.sh

Deploy Infra:
  stage: infra
  script:
    - echo "Start infra deployment."
    - ./ci/yc-vpc.sh
    - ./ci/yc-compute.sh
    - echo "Infra deployed."

Deploy Kubernetes:
  stage: kube
  script:
    - echo "Do your deploy here"

Destroy:
  stage: destroy
  script:
    - echo "Destroy infra"
    - ./ci/destroy.sh
  when: manual