- name: Install required pip package for Helm
  pip:
    name: [pyhelm, grpcio]

- name: Init Helm
  command: "{{bin_dir}}/helm init --client-only"

- name: Update Helm repo
  command: "{{bin_dir}}/helm repo update"
