---
#- hosts: localhost
#  connection: local
#  tasks:
#    - name: sleep for 3 minutes before kubernetes installation
#      pause:
#        minutes: 3

- hosts: k8s-cluster
  tasks:
    - name: Update package management cache (APT)
      apt:
        update_cache: yes