---
- name: Allow Nginx to listen on tcp port 6443
  seport:
    ports: 6443
    proto: tcp
    setype: http_port_t
    state: present

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Copy Nginx Config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

