- name: Allow Nginx to listen on tcp port 6443
  seport:
    ports: 6443
    proto: tcp
    setype: http_port_t
    state: present

- name: create cert directory
  file:
    path: /etc/pki/nginx/private
    state: directory

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Copy Certificate
  template:
    src: certificate.crt
    dest: /etc/pki/nginx/server.crt

- name: Copy Certificate Key
  template:
    src: private.key
    dest: /etc/pki/nginx/private/server.key

- name: Copy Nginx Config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Insert Index Page
  template:
    src: index.html
    dest: /usr/share/nginx/html/index.html

- name: Start NGiNX
  service:
    name: nginx
    state: restarted