- name: copy templates
  template:
    src: "{{ item.file }}.j2"
    dest: "/etc/kubernetes/manifests/{{ item.file }}"
  with_items:
    - {file: admin-sa.yml, type: serviceaccount, name: admin-sa}
    - {file: admin-crb.yml, type: clusterrolebinding, name: admin-crb}
  register: rbac_manifests

- name: add service accounts, bindings, etc.
  kube:
    name: "{{item.item.name}}"
    kubectl: "{{bin_dir}}/kubectl"
    resource: "{{item.item.type}}"
    filename: "/etc/kubernetes/manifests/{{item.item.file}}"
    state: "latest"
  with_items: "{{ rbac_manifests.results }}"

- name: get admin token
  command: kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}') | grep "token:" | awk '{print $2}'
  register: admin_token

- name: save admin token
  copy:
    content: "{{ admin_token.stdout }}"
    dest: "/home/{{ ansible_user }}/token.txt"

- name: Copy admin token to ansible host
  fetch:
    src: "/home/{{ ansible_user }}/token.txt"
    dest: "{{ inventory_dir }}/artifacts/token.txt"
    flat: yes
    validate_checksum: no